version: '3'

services:
  web:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-dev
    volumes:
      - ./src:/opt/app/src
    ports:
      - "8000:8000"
    env_file:
      - env/.env.dev
